### ISSUE TITLE
IUC09 midterm report MatWerk

### ISSUE THREAD

**Issue by mkuehbach** [FAIRmat-NFDI/nexus_definitions#245]
1d
- [x] Answer Chris E./Anika L. s' questions on PP and midterm report 0.25d
- [x] IUC09 midterm report Zenodo sheet written now waiting for feedback by the team
- [x] IUC07 midterm report Zenodo sheet written now waiting for feedback by the team
- [x] Update IUC09 status slide deck for AHOD for 1./2. July meeting 0.5d
- [x] Discuss with Marian B./Alexander H. how to for IUC07
0.25d

**Comment by lukaspie** [comment]
Closed as completed.
