### ISSUE TITLE
Promote NXcomponent_em to generic NXcomponent

### ISSUE THREAD

**Issue by mkuehbach** [FAIRmat-NFDI/nexus_definitions#253]

**Comment by mkuehbach** [comment]
Discussion on #250 by @lukaspie motivated to promote NXcomponent_em to a general base class NXcomponent that can be used by all methods (starting at least with those methods used in FAIRmat).
This issue is about implementing the respective change in the contributed base class NXcomponent_em.yaml and make the relevant modifications in NXem and using classes.

**Comment by lukaspie** [comment]
Closed as completed
