### ISSUE TITLE
Additions to NXmpes/NXinstrument

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/nexus_definitions#85]
There are some alterations desired for NXmpes/NXinstrument:

- [x] Add an NXtransformation to NXenergydispersion
- [x] Allow for torroidal analyzers
- [x] Allow for multiple angular resolutions (possibly already solved by NXresolution?)
- [x] Is there a type in NXbeam? If so rename/remove it so we only have probe.
- [x] Refactor NXsource docstring (there is no ring or facility!) #83 

[Meeting ref](https://github.com/FAIRmat-NFDI/data-modeling/blob/main/mpes/meetings/2023-10-18_additions_to_nxmpes_instrument.md#todos)

**Comment by lukaspie** [comment]
> Allow for torroidal analyzers

Is this only in NXenergydispersion? I.e. just extending the scheme enumeration?

**Comment by lukaspie** [comment]
>  Allow for multiple angular resolutions (possibly already solved by NXresolution?)

I guess one could just use the resolution(NXdata) field in NXresolution to have multiple values (e.g., in different momentum directions)

**Comment by domna** [comment]
I left a comment in #52. I think the `depends_on` should be listed directly under `NXenergydispersion` and not under another `NXtransformations`.

> Is there a type in NXbeam? If so rename/remove it so we only have probe.

Wasn't there anything duplicate? Or was it just the photon / x-ray ambiguity?
