### ISSUE TITLE
To fix comment alignment bug

### ISSUE THREAD

**Issue by RubelMozumder** [FAIRmat-NFDI/nexus_definitions#97]
While converting from yaml to nxdl and nxdl to yaml, the comment does not come on the same alignment as it is intended.

**Comment by RubelMozumder** [comment]
The changes also come with the PR [93](https://github.com/FAIRmat-NFDI/nexus_definitions/pull/93) that also contain changes for #87.

**Comment by lukaspie** [comment]
Can we close this? Nyaml is not part of the repo anymore.
